// <auto-generated> - Template:MapperDtoToSqliteModelDataAndMvvmLightModelObject, Version:2.0, Id:5078579f-7ab4-430d-9dcc-a3190f678efc
using objBlogger = ModelLibrary.ModelObj.Blogger;
using dataBlogger = ModelLibrary.ModelData.Blogger;
using dtoBlogger = ModelLibrary.DTO.Blogger;

namespace ModelLibrary
{
	public static partial class ModelMapper
	{

		#region ModelObj to ModelDto

		public static dtoBlogger.Blog ToDto(this objBlogger.Blog source)
		{
			return new dtoBlogger.Blog()
			{
				BlogId = source.BlogId,
				Url = source.Url,
			};
		}

		public static dtoBlogger.Post ToDto(this objBlogger.Post source)
		{
			return new dtoBlogger.Post()
			{
				BlogId = source.BlogId,
				Content = source.Content,
				PostId = source.PostId,
				Title = source.Title,
			};
		}


		#endregion ModelObj to ModelDto

		#region ModelData to ModelDto

		public static dtoBlogger.Blog ToDto(this dataBlogger.Blog source)
		{
			return new dtoBlogger.Blog()
			{
				BlogId = source.BlogId,
				Url = source.Url,
			};
		}

		public static dtoBlogger.Post ToDto(this dataBlogger.Post source)
		{
			return new dtoBlogger.Post()
			{
				BlogId = source.BlogId,
				Content = source.Content,
				PostId = source.PostId,
				Title = source.Title,
			};
		}


		#endregion ModelData to ModelDto

		#region ModelDto to ModelObj

		public static objBlogger.Blog ToModelObj(this dtoBlogger.Blog source)
		{
			return new objBlogger.Blog()
			{
				BlogId = source.BlogId,
				Url = source.Url,
			};
		}

		public static objBlogger.Post ToModelObj(this dtoBlogger.Post source)
		{
			return new objBlogger.Post()
			{
				BlogId = source.BlogId,
				Content = source.Content,
				PostId = source.PostId,
				Title = source.Title,
			};
		}


		#endregion ModelDto to ModelObj

		#region ModelDto to ModelData

		public static dataBlogger.Blog ToModelData(this dtoBlogger.Blog source)
		{
			return new dataBlogger.Blog()
			{
				BlogId = source.BlogId,
				Url = source.Url,
			};
		}

		public static dataBlogger.Post ToModelData(this dtoBlogger.Post source)
		{
			return new dataBlogger.Post()
			{
				BlogId = source.BlogId,
				Content = source.Content,
				PostId = source.PostId,
				Title = source.Title,
			};
		}


		#endregion ModelDto to ModelData
	}
}
