// <auto-generated> - Template:DTO, Version:2.0, Id:0d58c309-4b48-4464-819d-83c9c87cf463
using System;
namespace ModelLibrary.DTO.Blogger
{
	public partial class Blog
	{
		public Blog()
		{
			InitializePartial();
		}

		public int BlogId { get; set; } // Primary key
		public string Url { get; set; }


		partial void InitializePartial();

	}
}
