// <auto-generated> - Template:DTO, Version:2.0, Id:0d58c309-4b48-4464-819d-83c9c87cf463
using System;
namespace ModelLibrary.DTO.Blogger
{
	public partial class Post
	{
		public Post()
		{
			InitializePartial();
		}

		public int PostId { get; set; } // Primary key
		public int BlogId { get; set; }
		public string Content { get; set; }
		public string Title { get; set; }


		partial void InitializePartial();

	}
}
