// <auto-generated> - Template:SampleData, Version:2.0, Id:28f7acd7-ff48-4cd5-8068-2b234e52a11e
using System;

namespace ModelLibrary.ModelData.Blogger
{
	public static class DemoBlog
	{
		public static int SampleBlogId0000 = 1316708207;
		public static int SampleBlogId0100 = 1464559285;

		public static Blog SampleBlog00
		{
			get
			{
				return new Blog()
				{
					BlogId = SampleBlogId0000,
					Url = "SampleUrl",
				};
			}
		}
		public static Blog SampleBlog01
		{
			get
			{
				return new Blog()
				{
					BlogId = SampleBlogId0100,
					Url = "SampleUrl",
				};
			}
		}

	}
}
