// <auto-generated> - Template:SampleData, Version:2.0, Id:28f7acd7-ff48-4cd5-8068-2b234e52a11e
using System;

namespace ModelLibrary.ModelData.Blogger
{
	public static class DemoPost
	{
		public static int SamplePostId0000 = 30965217;
		public static int SamplePostId0100 = 1897586389;

		public static Post SamplePost00
		{
			get
			{
				return new Post()
				{
					PostId = SamplePostId0000,
					BlogId = 0,
					Content = "SampleContent",
					Title = "SampleTitle",
				};
			}
		}
		public static Post SamplePost01
		{
			get
			{
				return new Post()
				{
					PostId = SamplePostId0100,
					BlogId = 0,
					Content = "SampleContent",
					Title = "SampleTitle",
				};
			}
		}

	}
}
