// <auto-generated> - Template:MvvmLightModelObject, Version:2.0, Id:13213ee9-7e50-4dbd-82eb-9030fad28b26
using GalaSoft.MvvmLight;
using System;

namespace ModelLibrary.ModelObj.Blogger
{
	public partial class Post : ObservableObject
	{
		public Post()
		{

			InitializePartial();
		}

		private int _postId;
		private int _blogId;
		private string _content;
		private string _title;


		public int BlogId
		{
			get { return _blogId; }
			set
			{
				Set<int>(() => BlogId, ref _blogId, value);
				RunCustomLogicSetBlogId(value);
			}
		}

		public string Content
		{
			get { return _content; }
			set
			{
				Set<string>(() => Content, ref _content, value);
				RunCustomLogicSetContent(value);
			}
		}

		public int PostId
		{
			get { return _postId; }
			set
			{
				Set<int>(() => PostId, ref _postId, value);
				RunCustomLogicSetPostId(value);
			}
		}

		public string Title
		{
			get { return _title; }
			set
			{
				Set<string>(() => Title, ref _title, value);
				RunCustomLogicSetTitle(value);
			}
		}

		public virtual Blog Blog { get; set; } 


		partial void InitializePartial();

		#region RunCustomLogicSet

		partial void RunCustomLogicSetBlogId(int value);
		partial void RunCustomLogicSetContent(string value);
		partial void RunCustomLogicSetPostId(int value);
		partial void RunCustomLogicSetTitle(string value);

		#endregion RunCustomLogicSet

	}
}
