// <auto-generated> - Template:SqliteModelData, Version:2.0, Id:9ee14087-7b71-436b-b78a-47e5ff61a2d3
using SQLite;
using System;

namespace ModelLibrary.ModelData.Blogger
{
	[Table("Blog")]
	public partial class Blog
	{

		[PrimaryKey]
		public int BlogId { get; set; }

		public string Url { get; set; }
	}
}
